var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                   o            ",
   "                                                    o             xxx           ",
   "                                              o    xx      xx    x!!!x          ",
   "                                    o o      xx                  x!!!x          ",
   "                            o o                                    v xx         ",
   "                                   xxxxx                            v           ",
   "                           xxxx                                   v             ",
   "  x                             o o o    o o                                 x  ",
   "  x                             xxxxx                                        x  ",
   "  x                                      xxxxxxxxx!!!x                     o x  ",
   "  x                   o                           vvvx                       x  ",
   "  x  @        xxxx            x o x                  x     x                 x  ",
   "  xxxxxxxxxxxxx!!xxxxxxxxxxxxxx x xxxxxxxxxxxxxxxxxxxx  o  xxxxxxxxyyyxxxxxxxxx  ",
   "                              x   x                  x  x  x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                        xxxxxxxx                                                                  ",
   "                                         v  v vv                                                                  ",
   "                                                                   x    x                                         ",
   "                                                                   x    x                                         ",
   "                                                  v                x    x                                         ",
   "                                                              xxxxxxxxxxxxxxx             v                       ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                                         v   v                 xxxx!!!!!xxxx                                      ",
   "                                                                  xxxxxxx                    o                    ",
   "                                x x                                           v              x                    ",
   "                             x       x                                                       x                    ",
   "                              x     x x                                    v                 x                    ",
   "                                xxxx!!!x                                                   xxx                    ",
   "                                    x!!!x                   o  o                             x                    ",
   "                                    xx!!x               yy                                   x                    ",
   "                           xx   x     xx             xvvvvvxxxxx                      xx     x                    ",
   "             xx       xx        x o    v            xx         v                      x      x            |       ",
   "     @       x       | x |      x                    x         v           o          x      x                    ",
   "    xxx      x         x        x                    x         v         xxxxx   xxxxxx      x                    ",
   "   sx xs     x         x        x o    v       x     x         v           o     x           x                    ",
   "yyyyx xyyyyyyx |       x        x   x!!!!!!!!!!x     x ||||||| v           =     x          xx                    ",
   " =      =     =        =    |   x   xxxxxxxxxxx      x!!!!!!!xx|     xxxxxxxxxxxsxx    o o  xx     |              ",
   "!!!!x x!!!!!!x!!!!!!!!!x        x    o              xx!!!!!!xx |                  x        xx                     ",
   "!!!!x x!!!!!!x!!!!!!!!!x      | x                  xx!!!!!!xx  |                  yyyyysssyy            |         ",
   "!!!!x x!!!!!!x!!!!!|!!!x!!!!!!!!x     xsxxxxxxxxxxxx!!!!!!xx   |                                                  ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!!!!xyxxxxx!!!!!!!!!!!!!!!!!!xx    |                                                  ",
   "=               =               =                   =          |    |    =         =              =               "],
  ["vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                  y                       y               y            y                         y            ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  x                                                                                                           ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x     JUST KEEP SWIMMING SWIMMING SWIMMING      |xxxx|    |xxxx|                                         x  ",
   "  x    =           xxx                    x                              x         xxx                     x  ",
   "  x               ooooo       x           x                             xxx       x!!!x          x         x  ",
   "  x               ooooo       x           x                             x!x        xxx           x!        x  ",
   "  x                xxx        xyyyyyyyyyyyx  x    x    x    x    x     x!!!x                    xx!        x  ",
   "  x      @                    x           x!!x    x!!!!x    x!!!!x    x!!!!!x                    x!       ox  ",
   "  xxxxxxxsssssssssssxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxssssssxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["  =              v                                                                              v =           ",
   "                                                                        oo                                    ",
   "                                                                      xooox                                   ",
   "                                                                     oooooooo                                 ",
   "                                                                    oooooooooo                                ",
   "                                                                   xxxxxxxxxxxx                               ",
   "                                                                x oo          oo  x                           ",
   "                                                                 oooo        oooo                             ",
   "                                                                oooooo      oooooo                            ",
   "                                                       o       oooooooo    oooooooo                           ",
   "                                                      xxx     xxxxxxxxxx  xxxxxxxxxx                          ",
   "                                         o     xxx           xxxxxxxxxxxxxxxxxxxxxxxx                         ",
   "                          o             xxx    v                                                              ",
   "                              xxx                                                                             ",
   "                         xxx            ||                xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                  =   ",
   "                   xxx         xxx                                                                            ",
   "                                                                                o      o                      ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         yyy       xxxxxx                    x                                    ",
   "                                                                                                              ",
   "                                           sx                    ||                                           ",
   "  x        =                                                                               o                  ",
   "  x         x o xx!!!!!xx o xx!!!!!xx o ss                                          o      x                  ",
   "  x         x   x       x   x       x   x   x             ||                  x     x   x                     ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     yyyyy       xx     xx     yyy                      ||           ",
   "        x=                  =                 x   x                     xxx                                   ",
   "        xxxxxxxyyyyyyyxxxxxxxxxssssxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
